#Install services                                                     
---                                                                   
  - hosts: loadbalancers                                              
    become: true                                                      
    tasks:                                                            
      - name: installing apache                                       
        yum: name=httpd state=present                                 
  - hosts: webservers                                                 
    become: true                                                      
    tasks:                                                            
      - name: Installing servces                                      
        yum:                                                          
          name:                                                       
            - httpd                                                   
            - php                                                     
          state: present  