#setup-app.yml
---
  - hosts: webservers
    become: true

    vars:
      path_to_app: "/var/www/html"

    vars_files:
      - ../vars/secret-variables.yml

    tasks:
      - name: Use secret password
        debug:
          msg: "{{ secret_password }}"

      - name: Upload application file
        copy: 
          src: ../index.php
          dest: "{{ path_to_app }}"
          mode: 0755

      - name: Create simple info page
        copy: 
          dest: "{{ path_to_app }}/info.php"
          content: "<h1> IP address of of our webserver IP ADDRESS: {{ ansible_host}} and HOST: {{ ansible_hostname}}</h1>"

      - name: See directory contents
        command: ls -la {{ path_to_app }}
        register: dir_contents

      - name: Debug directory contents
        debug:
          msg: "{{ dir_contents }}"


      - name: Configure php.ini
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=Off'
        notify: restart apache
  
    handlers: 
        - name: restart apache
          service: name=httpd state=restarted


